---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-socks-frontend.name" . }}-int
  labels:
    {{- include "helm-socks-frontend.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
