apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sock-shop-front-end
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  description: Example Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: sock-shop-front-end*
    server: https://kubernetes.default.svc
  - namespace: argo
    server: https://kubernetes.default.svc
