apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: guestbook-workflow
spec:
  entrypoint: check-service-up
  onExit: exit-handler
  templates:
  - name: check-service-up
    container:
      image: curlimages/curl
      command: ['curl']
      args:
        - '-v'
        - '-X'
        - 'GET'
        - 'guestbook-ui.guestbook'

  - name: exit-handler
    steps:
    - - name: notify
        template: send-status-webhook

  - name: send-status-webhook
    container:
      image: curlimages/curl
      command: ['curl']
      args:
        - '-v'
        - '-X'
        - 'POST'
        - '-d'
        - '{"status":"{{workflow.status}}"}'
        - 'https://webhook.site/c1d94793-b1b1-424b-b412-3f429a6825bb'
